name: EKS Infra deployment

on:
    workflow_dispatch: 

jobs:
    terraform-deployment:
        name: Terraform deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.9.3"
            
            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            

            - name: Terraform initialize
              run : terraform init        
            
            - name: Terraform plan
              run: terraform plan


          

